import type { Metadata } from "next";
import "./globals.css";
import Provider from "@/app/Provider";
import { Suspense } from "react";
import Nav from "@/components/UI/Nav";
import { Jost, Poppins, IBM_Plex_Sans } from "next/font/google";
import ToastWrapper from "./ToastWrapper";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const jost = Jost({
  subsets: ["latin"],
});

const ibm = IBM_Plex_Sans({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700"],
});

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.className} antialiased`}
      >
        <Provider>
          <ToastWrapper />
          <Suspense fallback={<p>Loading...</p>}>
            <Nav />
            {children}
            {/* <Footer /> */}
          </Suspense>
        </Provider>
      </body>
    </html>
  );
}
